[window]

decorations = "Buttonless"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.9

[font]

normal.family = "JetBrains Mono"
size = 14

[keyboard]
bindings = [
    { key = "Space", mods = "Command|Shift", action = "ToggleViMode" }
]
